apiVersion: v1
kind: Service
metadata:
  name: prizedraw-realtime-gateway
  labels:
    app: realtime-gateway
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9094"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: realtime-gateway
  ports:
    - name: http
      port: 80
      targetPort: 9094
      protocol: TCP
